const members = [
  {
    id: 1,
    name: "김민수",
    major: "컴퓨터공학과",
    category: "프론트엔드",
    role: "프론트엔드",
    skills: ["React", "HTML", "CSS"],
    intro: "웹 프론트엔드 개발을 좋아합니다.",
    image: "profile1.jpg",
  },
  {
    id: 2,
    name: "정우진",
    major: "소프트웨어학과",
    category: "백엔드",
    role: "백엔드",
    skills: ["Node.js", "MongoDB", "API"],
    intro: "서버 개발과 데이터베이스 설계에 관심이 있습니다.",
    image: "profile2.jpg",
  },
  {
    id: 3,
    name: "박준호",
    major: "시각디자인과",
    category: "디자이너",
    role: "디자이너",
    skills: ["Figma", "Photoshop", "UI/UX"],
    intro: "사용자가 보기 편한 UI 디자인을 좋아합니다.",
    image: "profile3.jpg",
  },
  {
    id: 4,
    name: "이서연",
    major: "경영학과",
    category: "기획자",
    role: "기획자",
    skills: ["기획", "발표", "문서정리"],
    intro: "서비스 아이디어를 구상하고 발표하는 것을 좋아합니다.",
    image: "profile4.jpg",
  },
  {
    id: 5,
    name: "최다은",
    major: "예술공학과",
    category: "영상 편집",
    role: "영상 편집",
    skills: ["Premiere", "After Effects", "촬영"],
    intro: "영상 편집과 콘텐츠 제작에 관심이 있습니다.",
    image: "profile5.jpg",
  },
  {
    id: 6,
    name: "한지훈",
    major: "예술공학과",
    category: "3D/VFX",
    role: "3D/VFX",
    skills: ["Blender", "Nuke", "VFX"],
    intro: "3D 그래픽과 합성 작업을 좋아합니다.",
    image: "profile6.jpg",
  },
];
